pipeline {
    agent any
    environment {
          APP_NAME = "reddit-clone-pipeline"
    }
    stages {
         stage("Cleanup Workspace") {
             steps {
                cleanWs()
             }
         }
         stage("Checkout from SCM") {
             steps {
                script {
                    // Clone the repository with sparse-checkout
                    checkout([$class: 'GitSCM', 
                        branches: [[name: 'main']], 
                        doGenerateSubmoduleConfigurations: false, 
                        extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'k8s/*']]]], 
                        submoduleCfg: [], 
                        userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/karim0bkh/reddit-clone.git']]
                    ])
                }
            }
        }

            stage("Update the Deployment Tags") {
                steps {
                    sh """
                        cat k8s/deployment.yaml
                        sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' k8s/deployment.yaml
                        cat k8s/deployment.yaml
                    """
                }
            }

       stage("Push the changed deployment file to GitHub") {
    steps {
        // Navigate to the 'k8s' folder
        dir('reddit-clone/k8s') {
            // Add or modify files in the 'k8s' folder as needed
            sh """
                git config --global user.name "karim0bkh"
                git config --global user.email "karim.bkh19@gmail.com"
                git add ./deployment.yaml
                git commit -m "Updated Deployment Manifest"
            """
            
            // Push changes to GitHub
            withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                sh "git push origin main"
            }
        }
    }
}


    }
}